<?php
  function visitor_theme($existing, $type, $theme,$path){
    $path_templates = drupal_get_path('module','visitor')."/templates";
    return[
        'visitor-list' => [
            'variables' => [
                'visitor_list' => null,
                'visitor' => null
            ],
            'path' => $path_templates
        ]
    ];
  }

use Drupal\Core\Mail\MailManagerInterface;
use Drupal\Component\Utility\SafeMarkup;
use Drupal\Component\Utility\Html;

function visitor_mail($key, &$message, $params) {
  $options = array(
    'langcode' => $message['langcode'],
  );
  switch ($key) {
    case 'email_contacto':
      $header = array(
        'MIME-Version' => '1.0',
        'Content-Type' => 'text/html; charset=UTF-8; format=flowed; delsp=yes',
        'Content-Transfer-Encoding' => '8Bit',
        'X-Mailer' => 'Drupal'
      );
      if(count($params['Cc'])>0) $header['Cc'] = implode(',', $params['Cc']);
      $message['headers'] = $header;
      $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['message'];
      break;
  }
}


